name: an-daghda

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"  # Jaeger agent UDP
      - "6832:6832/udp"  # Jaeger agent UDP
      - "14268:14268"  # Jaeger collector HTTP
      - "14250:14250"  # Jaeger gRPC
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"